version: '3'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: 998159020507.dkr.ecr.us-east-1.amazonaws.com/todo-weed-repository/backend:$IMAGE_TAG
    volumes:
      - ./todos.db:/weed-app/go-weed-backend/todos.db
    ports:
      - "8081:8081"