version: '3'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: inai17ibar/go-weed-backend:latest
    volumes:
      - ./todos.db:/weed-app/go-weed-backend/todos.db
    ports:
      - "8081:8081"

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"