name: Go CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Get dependencies
      run: go get -v -t -d ./...

    - name: Set up Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose

    - name: Start MongoDB using Docker Compose
      run: |
        docker-compose -f docker-compose.yml up -d

    - name: Wait for MongoDB
      run: sleep 10

    - name: Run tests
      run: go test ./...
      env:
        API_KEY_GITHUB: ${{ secrets.API_KEY_GITHUB }}

    - name: Shutdown MongoDB
      run: |
        docker-compose -f docker-compose.yml down