name: Go CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}

    - name: Set up Go
    - uses: actions/setup-go@v4
      with:
        go-version: '1.21'
    
    - run: go get -v -t -d ./...
    - run: go test ./...